version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/spring-github-action
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop-admin.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start-admin.sh
      timeout: 60
