plugins {
    id 'java-library'
}

jar {
    enabled = true
}


group = 'com.nowait'
version = rootProject.version

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':nowait-common')

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // SWAGGER
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'

    compileOnly 'org.projectlombok:lombok:1.18.26'
    annotationProcessor 'org.projectlombok:lombok:1.18.26'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly  'org.junit.jupiter:junit-jupiter-engine'
}
